node {
  try {
    stage('build') {
      println('building...')
    }
    stage('test') {
      println('A test failed')
      sh 'exit 1'
    }
  } catch(error) {
    currentBuild.result = "FAILURE";

    slackSend (color: '#FF0000', message: "FAILED: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]' (${env.BUILD_URL})")

    throw error;
  }
}
